export const GET_DRIVERS = "GET_DRIVERS"
export const GET_DRIVERS_DETAIL = "GET_DRIVERS_DETAIL"
export const CLEAN_DETAIL = "CLEAN_DETAIL"
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const SEARCHBAR = "SEARCHBAR" 
export const ORDERCARD_DOB_ASC =  "ORDERCARD_DOB_ASC"
export const ORDERCARD_DOB_DESC =  "ORDERCARD_DOB_DESC"
export const SET_ORDER_BY_ASC = "SET_ORDER_BY_ASC"
export const SET_ORDER_BY_DESC = "SET_ORDER_BY_DESC"
export const CREATE_DRIVER= "CREATE_DRIVER"
export const GET_TEAM= "GET_TEAM"
export const FILTER_BY_DB= "FILTER_BY_DB"
export const FILTER_BY_API= "FILTER_BY_API"
export const FILTER_TEAM = "FILTER_TEAM"










// export const GET_DRIVERS = "GET_DRIVERS"
// export const GET_DRIVERS_DETAIL = "GET_DRIVERS_DETAIL"
// export const CLEAN_DETAIL = "CLEAN_DETAIL"
// export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
// export const SEARCHBAR = "SEARCHBAR" 
// export const ORDER_DRIVERS = " ORDER_DRIVERS";
// export const ORDER_BY_ORIGIN = "ORDER_BY_ORIGIN";
// export const CREATE_DRIVER= "CREATE_DRIVER"
// export const GET_TEAM= "GET_TEAM"
